using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

/// <summary>
/// The classes in this file represent the JSON schema for nuance_CALENDARX
/// This code was generated by GitHub Copilot
/// The schema used can be found here: https://docs.nuance.com/mix/reference/data_packs/predefined/latest/nuance_calendarx/#schema
/// </summary>

namespace SpeechEnabledTvClient.Services.Analyzer
{
    public class TimeAbs
    {
        [JsonPropertyName("nuance_TIME_ABS")]
        public NuanceTimeAbs? NuanceTimeAbs { get; set; }
    }

    public class NuanceTimeAbs
    {
        [JsonPropertyName("nuance_AMPM")]
        public string? NuanceAMPM { get; set; }

        [JsonPropertyName("nuance_MINUTE")]
        public int NuanceMinute { get; set; }

        [JsonPropertyName("nuance_HOUR")]
        public int NuanceHour { get; set; }

        [JsonPropertyName("nuance_MODIFIER")]
        public string? NuanceModifier { get; set; }
    }

    public class TimeRel
    {
        [JsonPropertyName("nuance_TIME_REL")]
        public NuanceTimeRel? NuanceTimeRel { get; set; }
    }

    public class NuanceTimeRel
    {
        [JsonPropertyName("nuance_INCREMENT")]
        public int NuanceIncrement { get; set; }

        [JsonPropertyName("nuance_STEP")]
        public string? NuanceStep { get; set; }

        [JsonPropertyName("nuance_MODIFIER")]
        public string? NuanceModifier { get; set; }

        [JsonPropertyName("nuance_TIME_ANCHOR")]
        public Time? NuanceTimeAnchor { get; set; }
    }

    public class DateAbs
    {
        [JsonPropertyName("nuance_DATE_ABS")]
        public NuanceDateAbs? NuanceDateAbs { get; set; }
    }

    public class NuanceDateAbs
    {
        [JsonPropertyName("nuance_DAY")]
        public int NuanceDay { get; set; }

        [JsonPropertyName("nuance_MONTH")]
        public int NuanceMonth { get; set; }

        [JsonPropertyName("nuance_YEAR")]
        public int NuanceYear { get; set; }

        [JsonPropertyName("nuance_MODIFIER")]
        public string? NuanceModifier { get; set; }
    }

    public class DateRel
    {
        [JsonPropertyName("nuance_DATE_REL")]
        public NuanceDateRel? NuanceDateRel { get; set; }
    }

    public class NuanceDateRel
    {
        [JsonPropertyName("nuance_NAMED_DAY")]
        public string? NuanceNamedDay { get; set; }

        [JsonPropertyName("nuance_DAY_OF_WEEK")]
        public int NuanceDayOfWeek { get; set; }

        [JsonPropertyName("nuance_INCREMENT")]
        public int NuanceIncrement { get; set; }

        [JsonPropertyName("nuance_STEP")]
        public string? NuanceStep { get; set; }

        [JsonPropertyName("nuance_MODIFIER")]
        public string? NuanceModifier { get; set; }

        [JsonPropertyName("nuance_DATE_ANCHOR")]
        public Date? NuanceDateAnchor { get; set; }
    }

    public class Date
    {
        [JsonPropertyName("nuance_DATE")]
        public object? NuanceDate { get; set; }
    }

    public class Time
    {
        [JsonPropertyName("nuance_TIME")]
        public object? NuanceTime { get; set; }
    }

    public class CalendarRange
    {
        [JsonPropertyName("nuance_CALENDAR_RANGE_START")]
        public CalendarRangeStart? NuanceCalendarRangeStart { get; set; }

        [JsonPropertyName("nuance_CALENDAR_RANGE_END")]
        public CalendarRangeEnd? NuanceCalendarRangeEnd { get; set; }
    }

    public class CalendarRangeStart
    {
        [JsonPropertyName("nuance_CALENDAR")]
        public object? NuanceCalendar { get; set; }
    }

    public class CalendarRangeEnd
    {
        [JsonPropertyName("nuance_CALENDAR")]
        public object? NuanceCalendar { get; set; }
    }

    public class CalendarX
    {
        [JsonPropertyName("nuance_CALENDARX")]
        public NuanceCalendarX? NuanceCalendarX { get; set; }
    }

    public class NuanceCalendarX
    {
        [JsonPropertyName("oneOf")]
        public List<NuanceCalendarOption> OneOf { get; set; } = new List<NuanceCalendarOption>();
    }

    public class NuanceCalendarOption
    {
        [JsonPropertyName("nuance_CALENDAR")]
        public object? NuanceCalendar { get; set; }

        [JsonPropertyName("nuance_CALENDAR_RANGE")]
        public CalendarRange? NuanceCalendarRange { get; set; }
    }
}